development:
  adapter: postgresql
  database: db_explorer
  username: robinbortlik
  password:

test:
  adapter: postgresql
  database: db_explorer_test
  username: robinbortlik
  password:

production:
  adapter: postgresql
  database: db_explorer
  username: robinbortlik
  password:
